class AddAttachmentImageToPosts < ActiveRecord::Migration[5.1]
  # Originally generated by Paperclip's `t.attachment :image` macro. Spelled out
  # here so the migration still runs after the move to Active Storage; the
  # columns themselves are dropped by RemovePaperclipImageFromPosts.
  def up
    change_table :posts do |t|
      t.string   :image_file_name
      t.string   :image_content_type
      t.integer  :image_file_size
      t.datetime :image_updated_at
    end
  end

  def down
    change_table :posts do |t|
      t.remove :image_file_name, :image_content_type, :image_file_size, :image_updated_at
    end
  end
end
